alnres = function(filein){
  qid = list()
  tid = list()
  seqid = list()
  alnlen = list()
  nmiss = list()
  ngap = list()
  qbegin = list()
  qend = list()
  tbegin = list()
  tend = list()
  evalue = list()
  bscore = list()
  feasco = list()
  qlabel = list()
  tlabel = list()
  f = readLines(filein)
  close(filein)
  for (line in f) {
    line = trimws(line, which = c("both", "left", "right"))
    temp1 = unlist(strsplit(line, split = "\\s+"))
    temp2 = unlist(strsplit(temp1[1], split = "\\|"))
    qid = c(qid, temp2[1])
    temp3 = unlist(strsplit(temp1[2], split = "\\|"))
    tid = c(tid, temp3[1])
    seqid = c(seqid, as.numeric(temp1[3]))
    alnlen = c(alnlen, as.integer((temp1[4])))
    nmiss = c(nmiss, as.integer((temp1[5])))
    ngap = c(ngap, as.integer((temp1[6])))
    qbegin = c(qbegin, as.integer((temp1[7])))
    qend = c(qend, as.integer((temp1[8])))
    tbegin = c(tbegin, as.integer((temp1[9])))
    tend = c(tend, as.integer((temp1[10])))
    evalue = c(evalue, as.numeric(temp1[11]))
    bscore = c(bscore, as.numeric(temp1[12]))
    qlabel = c(qlabel, temp2[2])
    tlabel = c(tlabel, temp3[2])
  }
  feasco = append(feasco, list(seqid, alnlen, nmiss, ngap, evalue, bscore))
  feature = feasco
  result = list(qid = qid, tid = tid, qlabel = qlabel, tlabel = tlabel, feature = feature)
  return(result)
}